[package]
name = "gossipers"
version = "0.1.0"
edition = "2018"
autors = ["Golubev Matvei <golubevmt@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = "0.39"
structopt = "0.3"
log = "0.4"
env_logger = "0.9"